CREATE TABLE RETAILERS (
  Retailer_ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(30) NOT NULL,
  Address_Line1 VARCHAR(50) NOT NULL,
  Address_Line2 VARCHAR(50) NULL,
  City VARCHAR(30) NOT NULL,
  Phone_Number DECIMAL(12,0) NULL,
  Website_URL VARCHAR(150) NULL,
  Email_Address VARCHAR(150) NULL,
  Updated_Date VARCHAR(50) NULL,
  PRIMARY KEY (Retailer_ID)
);

CREATE TABLE CUSTOMERS (
  Customer_ID INTEGER NOT NULL AUTO_INCREMENT,
  First_Name VARCHAR(30) NOT NULL,
  Last_Name VARCHAR(30) NOT NULL,
  Address_Line1 VARCHAR(50) NOT NULL,
  Address_Line2 VARCHAR(50) NOT NULL,
  City VARCHAR(30) NOT NULL,
  Phone_Number DECIMAL(15,0) DEFAULT NULL,
  DOB DATE NOT NULL,
  Updated_Date VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (Customer_ID)
);

CREATE TABLE USERS (
  User_ID INTEGER NOT NULL AUTO_INCREMENT,
  Email_Address VARCHAR(150) NOT NULL,
  PASSWORD VARCHAR(150) NOT NULL,
  RFID_Tag VARCHAR(20) NULL,
  Customer_ID INTEGER NULL,
  Acess_Level INTEGER NULL,
  Banned INTEGER DEFAULT 0,
  Updated_Date VARCHAR(50) NULL,
  PRIMARY KEY (User_ID),
  FOREIGN KEY (Customer_ID) REFERENCES CUSTOMERS (Customer_ID) ON DELETE CASCADE
);

CREATE TABLE GENRES (
  Genre_ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(30) NOT NULL,
  DESCRIPTION VARCHAR(200) NOT NULL,
  Minimum_Age INTEGER NOT NULL,
  Updated_Date VARCHAR(50) NULL,
  PRIMARY KEY (Genre_ID)
);

CREATE TABLE PUBLISHERS (
  Publisher_ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(30) NOT NULL,
  Address_Line1 VARCHAR(50) NOT NULL,
  Address_Line2 VARCHAR(50) NULL,
  Suburb VARCHAR(30) DEFAULT NULL,
  City VARCHAR(30) NOT NULL,
  Postcode DECIMAL(9,0) NULL,
  Phone_Number DECIMAL(15,0) NOT NULL,
  Website_URL VARCHAR(150) NULL,
  Updated_Date VARCHAR(50) NULL,
  PRIMARY KEY (Publisher_ID)
);

CREATE TABLE BOOKS (
  Book_ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  Author_Name VARCHAR(50) NOT NULL,
  Publication_Date DATE NOT NULL,
  Publisher_ID INTEGER NULL,
  Genre_ID INTEGER DEFAULT NULL,
  DESCRIPTION VARCHAR(1000) NOT NULL,
  Updated_Date VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (Book_ID),
  FOREIGN KEY (Publisher_ID) REFERENCES PUBLISHERS (Publisher_ID) ON DELETE SET NULL,
  FOREIGN KEY (Genre_ID) REFERENCES GENRES (Genre_ID) ON DELETE SET NULL
);

CREATE TABLE BOOKCOPIES (
  Book_Barcode DECIMAL(20,0) NOT NULL,
  Book_ID INTEGER NULL,
  Retailer_ID INTEGER NULL,
  Purchase_Price DECIMAL(19,4) NULL,
  RFID_Tag VARCHAR(30) NULL,
  Updated_Date VARCHAR(50) NULL,
  PRIMARY KEY (Book_Barcode),
  FOREIGN KEY (Book_ID) REFERENCES BOOKS (Book_ID) ON DELETE SET NULL,
  FOREIGN KEY (Retailer_ID) REFERENCES RETAILERS (Retailer_ID) ON DELETE SET NULL
);
CREATE TABLE BOOKSISSUED (
  Issue_Number INTEGER NOT NULL AUTO_INCREMENT,
  Customer_ID INTEGER NULL,
  Issue_Date DATE NOT NULL,
  Due_Date DATE NOT NULL,
  Returned_Date DATE NULL,
  Book_Barcode DECIMAL(20,0) DEFAULT NULL,
  PRIMARY KEY (Issue_Number),
  FOREIGN KEY (Book_Barcode) REFERENCES BOOKCOPIES (Book_Barcode) ON DELETE SET NULL,
  FOREIGN KEY (Customer_ID) REFERENCES CUSTOMERS (Customer_ID) ON DELETE SET NULL
);

CREATE TABLE BOOKSONHOLD (
  Hold_ID INTEGER NOT NULL AUTO_INCREMENT,
  Book_Barcode DECIMAL(20,0) DEFAULT NULL,
  DATE DATE NULL,
  Customer_ID INTEGER NULL,
  PRIMARY KEY (Hold_ID),
  FOREIGN KEY (Book_Barcode) REFERENCES BOOKCOPIES (Book_Barcode),
  FOREIGN KEY (Customer_ID) REFERENCES CUSTOMERS (Customer_ID)
);